### ISSUE TITLE
Stuck building quiz in ruby: 2 questions

### ISSUE THREAD

**Issue by michellecali** [michellecali/ajax_ruby#1]
Body:

I'm stuck, and could use some assistance. Two areas of concern: 

global.js line 43 - currently reads... is this right?
`check.open("get", "/server/" + string);
`

quiz_controller.rb lines 15 and 16 - I'm hoping this will result in hash converted to JSON (you'll see a binding.pry in the code, but because of what I'm thinking is the issue above, the program doesn't run far enough to see

Expected: line 43 submits a get request to /server/:string, where the string would look like [Blue,White,Brown], which would then be captured in params on quiz_controller.rb lines 6 & 7. 

Then, after being processed in the models, the resulting hash is converted to JSON on quiz_controller.rb lines 15 and 16, where it will subsequently be parsed in javascript and repopulate the layout.rb page.

Actual: Literally nothing happens. I click the submit button, the button disappears (as it should), but nothing appears. Console shows two errors being thrown:

global.js:43 GET http://localhost:9292/server/Blue,White,Brown 500 (Internal Server Error)(anonymous function) @ global.js:43

VM968:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0(anonymous function) @ global.js:30

**Comment by sumeetjain** [comment]
`check.open("get", "/server/" + string);` looks fine to me.

`global.js:43 GET http://localhost:9292/server/Blue,White,Brown 500 (Internal Server Error)(anonymous function) @ global.js:43`... This means that the error has nothing to do with JS. It's an error within the server itself, so you should debug it as you would if you were just building a Sinatra application along (with no AJAX component).

Looking at the server logs when that error occurs, I saw this:

```
::1 - - [27/Jul/2016:10:48:33 -0500] "GET /global.js HTTP/1.1" 304 - 0.0022
2016-07-27 10:48:48 - NameError - undefined local variable or method `q1' for Quiz:Class:
    /Users/sumeetjain/Code/michelle/app/models/quiz_models.rb:36:in `makeHash'
    /Users/sumeetjain/Code/michelle/app/controllers/quiz_controller.rb:12:in `block in <top (required)>'
```

That led me to this code in your model:

```
resultsHash[q1] = q1Result
resultsHash[q2] = q2Result
resultsHash[q3] = q3Result
```

I suspect the issue is that the keys being defined for your `resultsHash` are actually variables (references to some other value). But maybe you meant for them to be strings?

---

The response from the server, when you make a request to `"/server/" + string` is an HTML page telling you about the error (It's that familiar Sinatra's drink spilled over error page). Your JS code is then trying to parse _that_ as JSON. But it's not JSON! It's a full HTML page, describing the error you saw.

So I suspect your JSON formatting issues will go away once you resolve the back-end issue.

---

Also of note: The final line in your controller action is `puts JSON.generate(@resultsHash)`. You probably want `return JSON.generate(@resultsHash)`. `puts` will output the JSON to the terminal but it _returns `nil`_, so `nil` is what'll be send back as the server's response.

**Comment by michellecali** [comment]
Brilliant direction. It's working! Thanks!
